In [1]:
import pandas as pd
import numpy as np
from statistics import mode

In [2]:
data=[-19.2,23,24,32,45,12,43,67,45,32,56,32,100]

In [3]:
# Mean Median Mode
mean=np.mean(data)
mode=mode(data)
median=np.median(data)

In [5]:
data_copy=data.copy()
data

[-19.2, 23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32, 100]

In [6]:
# custom Logic for mean
sum=0
no_of_elements=len(data)
for val in data:
    sum+=val
print(f"Mean is : {sum/no_of_elements}")

Mean is : 37.830769230769235


In [7]:
# Other Way
print(np.sum(data)/len(data))

37.830769230769235


In [8]:
# Dispersion of Data 1.Percentile 2.standard Deviation 3.Variance
np.percentile(data,[25])


array([24.])

In [9]:
np.percentile(data,[25,50])

array([24., 32.])

In [10]:
np.percentile(data,[25,50,75])

array([24., 32., 45.])

In [11]:
np.percentile(data,[25,50,75,100])  # Quartile

array([ 24.,  32.,  45., 100.])

In [12]:
# IQR
# to calculate IQR We need q3 ,q1 calculated below

q3=np.percentile(data,[75])
q1=np.percentile(data,[25])
IQR=q3-q1
IQR

array([21.])

In [13]:
# Calculate Upperbond ,lowerbond

upper_bound=(q3+1.5*IQR)
lower_bound=(q1-1.5*IQR)

In [14]:
lower_bound

array([-7.5])

In [15]:
upper_bound

array([76.5])

In [16]:

# Finding Outliers

outliers=[]
for val in data:
    if val>upper_bound:
        outliers.append(val)
    elif val<lower_bound:
        outliers.append(val)
print(outliers)


[-19.2, 100]


In [17]:
data

[-19.2, 23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32, 100]

In [18]:
# Elimnating Ouliers
for val in outliers:
    data.remove(val)
data

[23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32]

In [19]:
# Variance and Standard Deviation

# variance 
np.var(data)

226.23140495867773

In [20]:
#standard Deviation
np.std(data)
np.float64(15.040990823701666)

15.040990823701666

In [21]:
#standard Deviation
np.std(data)

15.040990823701666

In [22]:
# MANUAL LOGIC FOR VARIACNE CALCULATIONS
data


[23, 24, 32, 45, 12, 43, 67, 45, 32, 56, 32]

In [23]:
# Population Variance 
sum=0
lengthh=len(data)

for val in data:
    sum+=(val-np.mean(data))**2
pvariance=sum/lengthh       
print(pvariance)

226.23140495867773


In [24]:
# Sample Variance 
sum=0
lengthh=len(data)

for val in data:
    sum+=(val-np.mean(data))**2
svariance=sum/(lengthh-1)      
print(svariance)

248.8545454545455


In [25]:
# Using Statistics Libraray
import statistics
statistics.pvariance(data)

226.23140495867767

In [26]:
statistics.variance(data)

248.85454545454544

In [27]:
# Population Standard Deviation
pstd=pvariance**0.5
pstd


15.040990823701666

In [29]:
statistics.stdev(data)    # sample std

15.775124261144361

In [28]:
statistics.pstdev(data)    # poplutaion std

15.040990823701664