Creating arrays One Dimensional

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])    # Method 1 
arr1=np.asarray([1,2,3,4,5,6]) # Method 2 

print(arr)
print(arr1)

[1 2 3 4 5 6]
[1 2 3 4 5 6]


Creating arrays 2 Dimensional

In [2]:
two_D=np.array([[1,2,5],[2,4,4]])
print(two_D)
print(two_D.ndim)

[[1 2 5]
 [2 4 4]]
2


Creating arrays 3 Dimensional

In [3]:
three_D=np.array([[[1,2,3],[2,4,5]],[[1,2,1],[2,3,2]]])
print(three_D)
print(three_D.ndim)

[[[1 2 3]
  [2 4 5]]

 [[1 2 1]
  [2 3 2]]]
3


In [4]:
empty=np.empty((2,3))
empty

array([[3.33772792e-307, 4.22786102e-307, 2.78145267e-307],
       [4.00537061e-307, 9.45656391e-308, 0.00000000e+000]])

In [5]:
zeros=np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
ones=np.ones((5,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
specific=np.full((3,6),255)
specific

array([[255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255]])

In [8]:
identity=np.identity(4)
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [9]:
# Creating A Dataframe
import pandas as pd
df=pd.DataFrame(np.random.rand(5,6),columns=["c1","c2","c3","c4","c5","c6"],index=['r1','r2','r3','r4','r5',])
df

c1        c2        c3        c4        c5        c6
r1  0.303200  0.813903  0.945572  0.427730  0.218491  0.193763
r2  0.495883  0.845055  0.092395  0.230624  0.941294  0.558509
r3  0.981349  0.194342  0.848145  0.706963  0.186060  0.278082
r4  0.678871  0.336139  0.162993  0.495396  0.923944  0.320154
r5  0.637617  0.386917  0.122583  0.533048  0.614139  0.535648

In [10]:
# Linspace : evenly spaced values syntax start end(inclusive) no_of_elemnets

arr1=np.linspace(0,1,10)
arr1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [11]:
# Logspace : Numbers spaced evenly on a log scale

np.logspace(1,10,5)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [12]:
# Slicing

a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [13]:
a[1:4]

array([2, 3, 4])

In [14]:
a[-2]

4

In [15]:
# 2d Array

ab=np.array([[1,2,3],
             [4,5,6]])
ab

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
ab[:,1:3]

array([[2, 3],
       [5, 6]])

In [17]:
ab[0][1]

2

In [18]:
ab[0,1]

2

In [19]:
ab[0]

array([1, 2, 3])

In [20]:
ab[0:2,1:2]

array([[2],
       [5]])