In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
arr2=arr*2
arr2

array([ 2,  4,  6,  8, 10, 12])

In [2]:
arr2=np.array([[1,2,3],[4,5,6]])*2
arr2
x=np.array([1,2,3])
y=np.array([1,2,3])
x+y

array([2, 4, 6])

In [3]:
x=np.array([1,2,3])
y=np.array([[1,2,3],[4,5,6]])
x+y
a=np.array([[1],[2],[3]])
b=np.array([4,5,6])
a*b

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [5]:
a=np.array([[1],[2],[3]])
b=np.array([4,5,6])
a*b


array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [6]:

a=np.array([1,2,3])
b=np.array([5,4,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[6 6 9]
[-4 -2 -3]
[ 5  8 18]
[0.2 0.5 0.5]


In [7]:
# Log exponentials etc
np.log(np.array([1,2,3]))

array([0.        , 0.69314718, 1.09861229])

In [8]:
np.exp(np.array([1,2,3]))

array([ 2.71828183,  7.3890561 , 20.08553692])

In [9]:
np.log10(np.array([1,2,3]))

array([0.        , 0.30103   , 0.47712125])

In [10]:
# Different airthamatic opearations on arrays
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.add(arr1,arr2)

array([5, 7, 9])

In [11]:
np.multiply(arr1,arr2)

array([ 4, 10, 18])

In [12]:
np.divide(arr2,arr1)

array([4. , 2.5, 2. ])

In [13]:
np.subtract(arr1,arr2)

array([-3, -3, -3])

In [14]:
np.power(arr1,arr2)

array([  1,  32, 729])

In [15]:
# Linear Algebra

np.dot(arr1,arr1)    # dot product

14

In [16]:
#Transpose
a=np.array([[1,2],[3,4]])
b=np.array([[5,3],[7,4]])
print(a.T)  # Transpose of A
print(b.T)  # Transpose of B

[[1 3]
 [2 4]]
[[5 7]
 [3 4]]


In [17]:
# Inversion of a Matrix

np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [18]:
# Eigen Values and Eigen Vectors
w,v=np.linalg.eig(a)
print("eigen values : ",w)
print("eigen vector : ",v)

eigen values :  [-0.37228132  5.37228132]
eigen vector :  [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
