In [1]:
# We can save any array in the txt , csv , npy npz format

import numpy as np
a=np.array([1,2,3,4,5,6])  # array to be saved
np.save("test",a)   # saves as npy
np.savez('test',array=a)  # saves as npz
np.savetxt('test.txt',a) # saves as txt

In [2]:
# Loads the saved file now
b=np.loadtxt('test.txt')
b

array([1., 2., 3., 4., 5., 6.])

In [3]:
c=np.load('test.npz')
c['array']

array([1, 2, 3, 4, 5, 6])

In [4]:
d=np.load('test.npy')
d

array([1, 2, 3, 4, 5, 6])